# Generated by Django 4.2.2 on 2023-06-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['id'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='viewer',
            options={'ordering': ['id'], 'verbose_name': 'Viewer', 'verbose_name_plural': 'Viewers'},
        ),
    ]
