# Generated by Django 4.1.7 on 2023-05-06 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0003_alter_ticket_row_alter_ticket_seat_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='phone',
        ),
        migrations.AlterField(
            model_name='viewer',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
    ]
