# Generated by Django 4.1.7 on 2023-05-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0005_viewer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='phone',
        ),
    ]
