# Generated by Django 4.1.7 on 2023-06-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0009_alter_ticket_row_alter_ticket_seat_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='viewer',
            new_name='viewer1',
        ),
        migrations.AddField(
            model_name='viewer',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afisha_app.ticket'),
        ),
    ]
