# Generated by Django 4.1.7 on 2023-06-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0011_remove_viewer_tickets_viewer_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='surname',
        ),
    ]
