# Generated by Django 4.1.7 on 2023-06-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0012_remove_viewer_name_remove_viewer_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='surname',
            field=models.CharField(max_length=40, null=True, verbose_name='surname'),
        ),
    ]
