# Generated by Django 4.1.7 on 2023-06-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0014_remove_viewer_name_remove_viewer_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='viewer1',
            new_name='viewer_name',
        ),
    ]
