# Generated by Django 4.1.7 on 2023-06-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0015_rename_viewer1_ticket_viewer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='viewer_name',
            new_name='viewer',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='tickets',
        ),
    ]
