# Generated by Django 4.1.7 on 2023-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0016_rename_viewer_name_ticket_viewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='name',
            field=models.CharField(max_length=40, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='viewer',
            name='surname',
            field=models.CharField(max_length=40, null=True, verbose_name='surname'),
        ),
    ]
