# Generated by Django 4.1.7 on 2023-06-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0017_viewer_name_viewer_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='surname',
        ),
    ]
