# Generated by Django 4.1.7 on 2023-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0018_remove_viewer_name_remove_viewer_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='viewer',
            new_name='users',
        ),
        migrations.AddField(
            model_name='viewer',
            name='tickets',
            field=models.ManyToManyField(through='afisha_app.ViewerTicket', to='afisha_app.ticket'),
        ),
    ]
