# Generated by Django 4.1.7 on 2023-06-07 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0020_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='tickets',
        ),
        migrations.AddField(
            model_name='viewer',
            name='events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afisha_app.event'),
        ),
    ]
