# Generated by Django 4.1.7 on 2023-06-07 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('afisha_app', '0021_remove_ticket_price_remove_viewer_tickets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='events',
        ),
        migrations.CreateModel(
            name='EventViewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afisha_app.event')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afisha_app.viewer')),
            ],
            options={
                'db_table': '"afisha"."event_viewer"',
                'unique_together': {('event', 'viewer')},
            },
        ),
        migrations.AddField(
            model_name='viewer',
            name='events',
            field=models.ManyToManyField(through='afisha_app.EventViewer', to='afisha_app.event'),
        ),
    ]
